### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by davemcnally** [davemcnally/awebot#1]
- [x] Lower the point earn rate when offline
- [x] Command for a sorted list of top points
- [x] Command for a sorted list of top hours
- [x] Fix raffles to function without looping through first
- [ ] Add a quote system
- [ ] Add a voting system
- [ ] Sort editor status for bot to update stream
- [ ] Check names against the API where possible
- [x] Others cannot enter raffles
